// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7puGHbmGVcSp_vxX3ot540MtyKC0_F60',
    appId: '1:557599926527:web:1789d346c3017537c084ca',
    messagingSenderId: '557599926527',
    projectId: 'trenapp-ddc3d',
    authDomain: 'trenapp-ddc3d.firebaseapp.com',
    storageBucket: 'trenapp-ddc3d.firebasestorage.app',
    measurementId: 'G-FGW47EXBRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChIMGCobMC4TW39C5KKBDVxwgQi4wUKK8',
    appId: '1:557599926527:android:4978ab713e231e62c084ca',
    messagingSenderId: '557599926527',
    projectId: 'trenapp-ddc3d',
    storageBucket: 'trenapp-ddc3d.firebasestorage.app',
  );
}
